"""

47. Permutations II
Difficulty: Medium
Link: https://leetcode.com/problems/permutations-ii/

PROBLEM:
Given a collection of numbers nums that might contain duplicates,
return all possible unique permutations in any order.

Example 1:
Input: nums = [1, 1, 2]
Output:
[
    [1, 1, 2],
    [1, 2, 1],
    [2, 1, 1]
]

Example 2:
Input: nums = [1, 2, 3]
Output:
[
    [1, 2, 3],
    [1, 3, 2],
    [2, 1, 3],
    [2, 3, 1],
    [3, 1, 2],
    [3, 2, 1]
]

APPROACH:
Use backtracking.

The main challenge is avoiding duplicate permutations.

First, sort nums.
This puts equal numbers next to each other.

Then use a used array to track which indices are already included
in the current permutation.

To avoid duplicates:
If nums[i] is the same as nums[i - 1], and nums[i - 1] has not been used
in the current path, we skip nums[i].

Why?
Because choosing the second duplicate before the first duplicate would create
the same permutation that was already generated by choosing the first duplicate.

When the current permutation length equals len(nums), add a copy to the result.

Time Complexity: O(n * n!)
Space Complexity: O(n)

where:
n = len(nums)

In the worst case, all numbers are unique, so there are n! permutations.
Copying each permutation takes O(n).

"""

from typing import List


class Solution:
    def permuteUnique(self, nums: List[int]) -> List[List[int]]:

        nums.sort()

        result = []
        current_permutation = []
        used = [False] * len(nums)

        def backtrack() -> None:
            if len(current_permutation) == len(nums):
                result.append(current_permutation.copy())
                return

            for i in range(len(nums)):
                if used[i]:
                    continue

                if i > 0 and nums[i] == nums[i - 1] and not used[i - 1]:
                    continue

                current_permutation.append(nums[i])
                used[i] = True

                backtrack()

                current_permutation.pop()
                used[i] = False

        backtrack()

        return result


# --- Tests ---
if __name__ == "__main__":
    solution = Solution()

    print(solution.permuteUnique([1, 1, 2]))
    # [
    #     [1, 1, 2],
    #     [1, 2, 1],
    #     [2, 1, 1]
    # ]

    print(solution.permuteUnique([1, 2, 3]))
    # [
    #     [1, 2, 3],
    #     [1, 3, 2],
    #     [2, 1, 3],
    #     [2, 3, 1],
    #     [3, 1, 2],
    #     [3, 2, 1]
    # ]

    print(solution.permuteUnique([1, 1, 1]))
    # [[1, 1, 1]]

    print(solution.permuteUnique([2, 2, 1, 1]))
    # [
    #     [1, 1, 2, 2],
    #     [1, 2, 1, 2],
    #     [1, 2, 2, 1],
    #     [2, 1, 1, 2],
    #     [2, 1, 2, 1],
    #     [2, 2, 1, 1]
    # ]
